name: Nightly Build

on:
  schedule:
    - cron: "* 0 * * *" # Minutes Hours DayOfMonth Month DayOfWeek

  workflow_dispatch:


jobs:
  assemble:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4.2.2
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Bump version
        uses: chkfung/android-version-actions@v1.2.2
        with:
          gradlePath: app/build.gradle.kts

      - name: Assemble APK
        run: ./gradlew assemble

