name: Nightly Build

on:
  schedule:
    - cron: "* 0 * * *" # Minutes Hours DayOfMonth Month DayOfWeek

  workflow_dispatch:


jobs:
  assemble:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4.2.2
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Bump version
        uses: chkfung/android-version-actions@v1.2.2
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{github.run_number}}

      - name: Assemble APK
        run: ./gradlew assemble

      - name: Store APK
        uses: actions/upload-artifact@v4
        with:
          name: architect-coders-unsigned.apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk

  distribute:
    needs: assemble
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: architect-coders-unsigned.apk
          path: app/build/outputs/apk/release/
      - name: Setup Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: /home/runner/work/architect-coders/architect-coders/app/build/outputs/apk/release/architect-coders-unsigned.apk