name: Release & Deploy

on:
  push:
    branches:
      - "release/*"

jobs:
  assemble:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.2
        with:
          java-version: 17
          distribution: "temurin"
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Bump version
        uses: chkfung/android-version-actions@v1.2.2
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{github.run_number}}

      - name: Store api secret
        run: echo ${{ secrets.API_PROPERTIES_FILE }} > api.properties.encoded

      - name: Decode api.properties
        run: base64 --decode api.properties.encoded > api.properties

      - name: Assemble APK
        run: ./gradlew assemble

      - name: Upload apk
        uses: actions/upload-artifact@v4
        with:
          name: Release APK
          path: app/build/outputs/apk/release/app-release-unsigned.apk