name: Release & Deploy

on:
  push:
    branches:
      - "release/*"

jobs:
  assemble:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.2
        with:
          java-version: 17
          distribution: "temurin"
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Bump version
        uses: chkfung/android-version-actions@v1.2.2
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{github.run_number}}

      - name: Store api secret
        run: echo ${{ secrets.API_PROPERTIES_FILE }} > api.properties.encoded

      - name: Decode api.properties
        run: base64 --decode api.properties.encoded > api.properties

      - name: Store google-services.json.encoded
        run: echo ${{ secrets.GOOGLE_SERVICES_JSON }} > google-services.json.encoded

      - name: Decode google-services.json
        run: base64 --decode google-services.json.encoded > app/google-services.json

      - name: Assemble AAB
        run: ./gradlew bundleRelease

      - name: Upload apk
        uses: actions/upload-artifact@v4
        with:
          name: Release AAB
          path: app/build/outputs/bundle/release/app-release.aab

  sign:
    runs-on: ubuntu-latest
    needs: assemble

    steps:
      - uses: actions/checkout@v4

      - name: Download aab
        uses: actions/download-artifact@master
        with:
          name: Release AAB
          path: ./

      - name: Sign AAB
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: ./
          signingKeyBase64: ${{ secrets.SIGNING_FILE }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ALIAS_PASSWORD }}

      - name: Upload AAB Signed
        uses: actions/upload-artifact@v4
        with:
          name: Release AAB Signed
          path: ./app-release.aab
